- name: restart ssh
  service:
    name: ssh
    state: restarted
    daemon_reload: yes

- name: restart networking
  service:
    name: networking
    state: restarted
    daemon_reload: yes

- name: docker status
  service:
    name: docker
    state: started
